### PR TITLE
implement Clone trait for PathTree

### PR DESCRIPTION
**Pull request by kotlin2018**

### CODE REVIEW

**Comment by fundon** [comment]
I'm interested in what scenarios require clone the entire tree?

**Comment by kotlin2018** [comment]
> I'm interested in what scenarios require clone the entire tree?
For example, I have defined a routing tree. There is a method in this routing tree that needs the tree field to implement Clone trait

image

**Comment by fundon** [comment]
rebase codes, `.idea` `.vscode` `.fleet` should not be commited and fmt it.

**Comment by fundon** [comment]
@kotlin2018 Please rebase it? Thank you.

**Comment by fundon** [comment]
You can reopen it if you want to continue.

**Pull request closed without merging**
